ci: add shellcheck to CI workflow

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -20,10 +20,30 @@ jobs:
     - name: Check
       shell: bash
       run: |
-        # Run code formatting check
+        set +o pipefail
+
+        # Determine the two commits to be compared
+        if [ "$GITHUB_BASE_REF" ]; then # is pull_request event
+          before_commit=${{ github.event.pull_request.base.sha }}
+        else # is push event
+          if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
+            before_commit="HEAD~1"
+          else
+            before_commit=${{ github.event.before }}
+          fi
+        fi
+        after_commit=$GITHUB_SHA
+        echo "before_commit: ${before_commit} after_commit: ${after_commit}"
+        git fetch origin "${before_commit}" --depth=1
+
+        # Run Shell code issues check
+        git diff --name-only "${before_commit}".."${after_commit}" | grep '\.rs$' | xargs --no-run-if-empty ls -1df 2>/dev/null | xargs --no-run-if-empty shellcheck || { echo "shell check failed and exit"; exit 1; }
+        echo 'Shell code issues check passed.'
+
+        # Run Rust code formatting check
         has_issues=0
-        for file in $(git diff --name-only ${{ github.event.before }}..${{ github.event.after }} | grep '\.rs$'); do
-            if [ -f ${file} ] && ! rustfmt --edition 2018 --check --color auto ${file}; then
+        for file in $(git diff --name-only "${before_commit}".."${after_commit}" | grep '\.rs$'); do
+            if [ -f "${file}" ] && ! rustfmt --edition 2018 --check --color auto "${file}"; then
                 echo ""
                 has_issues=1
             fi
@@ -34,6 +54,7 @@ jobs:
             echo 'Code formatting issues detected.'
             exit 1
         fi
+
         # Run clippy check
         cargo clippy
     - name: Build
